# Generated by Django 4.2.5 on 2023-10-25 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nivel',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Usuario Normal'), (2, 'Usuario con Subscripción A'), (3, 'Usuario con Subscripción B')], default=1),
        ),
    ]
